config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'

  get 'messages/destroy'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact_us'

  devise_for :users
  resources :posts do
      resources :comments, shallow: true
  end
  root "static_pages#home"

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  # The next two can be put as members of users
  #get 'users/:id/posts/', to: 'users#user_posts', as: 'users_posts'
  #get 'users/:id/comments', to: 'users#user_comments', as: 'users_comments'
  # so we can see users profile 
  resources  :users do
    get 'posts', on: :member
    get 'comments', on: :member
    get 'messages', on: :member
    #resources :messages, shallow: true
  end
  resources :messages

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :body, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  # in the next two, the foriegn_key is determined by rails to be sender_id amd receiver_id
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  validates :sender_id, presence: true
  validates :receiver_id, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts,    dependent:   :destroy
  # XXX should the next have been through: posts  ... but they are not his posts
  has_many :comments, dependent:   :destroy
  # messages that the user sends to other users
  has_many :sent_messages, class_name: 'Message', 
                      foreign_key: 'sender_id',
                      dependent:   :destroy
  # messages that the user receives from other users
  has_many :messages, class_name: 'Message', 
                      foreign_key: 'receiver_id',
                      dependent:   :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    # Confirms a logged in user
    def logged_in_user
      unless user_logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    # I need to allow user_id here too since i am updating it as a hidden field.
    # Or else I could have added it here ??
    @comment = @post.comments.create(params[:comment].permit(:name, :body, :user_id))

    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(param[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    #$stderr.puts "PARAMS::: #{params[:message].keys}"
    id = params[:message][:receiver_id]
    @user = User.find(id)
    # I need to allow user_id here too since i am updating it as a hidden field.
    # Or else I could have added it here ??
    @message = @user.messages.create(params[:message].permit(:body, :sender_id, :receiver_id))

    redirect_to user_path(@user)
  end

  def destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    #@posts = Post.all.order("created_at DESC")
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end
  def new
    @post = current_user.posts.new
    #@post = current_user.posts.new
  end
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_url
    else
      render 'new'
    end
  end
  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

    # post and comment already have a default scope so they are ordered on created_at DESC
    @new_posts = Post.limit(10)
    @new_comments = Comment.limit(10)
    # http://stackoverflow.com/questions/2919720/how-to-get-record-created-today-by-rails-activerecord
    @new_users = User.where("created_at >= ?", Time.zone.now.beginning_of_day)
    #add_index :posts, :created_at
  end

  def help
  end

  def about
  end

  def contact_us
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # display a list of users paginated
  def index
    @users = User.all.order(:created_at).paginate( page: params[:page] )
  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    #@user = User.new(user_params)
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # handle a successful update
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  # profile page of user. user_path or link_to current_user
  def show
    @user = User.find(params[:id])
    # prevent viewing of user that is not activated
    #redirect_to root_url and return unless @user.activated?
    #@microposts = @user.microposts.paginate( page: params[:page] )
    @comments = @user.comments.order("created_at DESC").take(10)
    @comment_count = @user.comments.count
    @posts = @user.posts.order("created_at DESC").take(10)
    @post_count = @user.posts.count
    # last 10 messages
    @messages = @user.messages.order("created_at DESC").take(10)
    @message_count = @user.posts.count
  end
  # all comments of the user
  def comments
    @user = User.find(params[:id])
    #@comments = Comment.where("user_id = ?", @user.id).order("created_at DESC")
    @comments = @user.comments.order("created_at DESC")
  end
  # all posts of the user
  def posts
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC")
  end
  # all messages of the user
  # XXX these 3 should be paginated
  def posts
    @user = User.find(params[:id])
    @messages = @user.messages.order("created_at DESC")
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :sex, :location, :avatar, :signature, :dob)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title( page_title = '')
    base_title = "Blog App"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if false %>
<div class="comment clearfix">
    <div class="comment_content">
        <p class="comment_name"><strong><%= comment.user.name %></strong></p>
        <p class="comment_time">
        Submitted <%= time_ago_in_words(comment.created_at) %> ago
        </p>
        <p class="blockquote_style2"><%= comment.body %></p>
    </div>
</div>
<% end %>
<blockquote>
  <%= comment.body.html_safe %>
        <footer>
          <%= link_to "#{comment.user.name}", user_path(comment.user)  %>,
          <%= time_ago_in_words(comment.created_at) %> ago
          <!-- don't show a link to the post if the comments are shown on the same post page -->
          <% if !current_page?(post_path(comment.post)) %>
            in <%= link_to comment.post.title, comment.post %>
        <% end %>
        </footer>
</blockquote>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build(user_id: current_user.id)]) do |f| %>
    <%= f.hidden_field :user_id, value:  current_user.id %>
    <%= f.input :body , label: false, placeholder: "Say something" %>
    <%= f.button :submit %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
      <small>
              The blog app
      </small>
      <nav>
                          <ul>
                              <li><%= link_to "About", about_path %></li>
                              <li><%= link_to "Contact", contact_path %></li>
                              <li><a href="http://news.railstutorial.org/">News</a>
                              </li>
                          </ul> 
      </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
   <div class="container">
      <%= link_to "My Blogger", root_path, id: "logo" %> 
      <nav>
        <ul class="nav navbar-nav navbar-right"> 
           <li><%= link_to "Home", root_path %></li> 
           <li><%= link_to "Help", help_path %></li> 
           <% if false %>
           <% if logged_in? %>
               <li><%= link_to "Users", users_path  %></li>
               <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       Account <b class="caret"></b>
                   </a>
                   <ul class="dropdown-menu">
                       <li><%= link_to "Profile", current_user %></li>
                       <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                       <li class="divider"></li>
                       <li>
                           <%= link_to "Log out", logout_path, method: :delete %>
                       </li>
                   </ul>
               </li>
           <% else %>
               <li><%= link_to "Log in", login_path %></li>
           <% end %>
           <% end %>
        </ul> 
      </nav>
   </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Home", root_path %></li>
      <li><%= link_to "All Posts", posts_path %></li>
			<li><%= link_to "Members", users_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://twitter.com/lemonysnicket">Twitter</a></li>
			<li><a href="http://instagram.com/lemonysnicket">Instagram</a></li>
			<li><a href="https://bitbucket.org/lemony_snicket/bloggy">Github</a></li>
			<li><a href="mailto:bitbucket.qxv@gishpuppy.com">Email</a></li>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Login", new_user_session_path %></p>
		<% end %>
	</div>

	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<%= link_to "All Posts", posts_path %>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to Home", root_path %>
			<% end %>

			<% if user_signed_in? %>
				<div class="buttons">
          <p>User: <strong>
          <%= link_to "#{current_user.name}", current_user %>
          </strong></p>
          <%= link_to new_post_path, class: 'button btn-default' do %>
            New Post 
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'button btn-default' do %>
            Log Out
          <% end %>
				</div>
      <% else %>
				<div class="buttons">
          <%= link_to new_user_session_path, class: 'button btn-default' do %>
            Log In
          <% end %>
				</div>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>

        <%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/messages/_message.html.erb
<li>
    <span class="content">
      <strong><%= link_to "#{message.sender.name}", user_path(message.sender)  %></strong>: 
        <%= message.body.html_safe %> 
    </span>
    <span class="timestamp">
    Posted at:
    <%= message.created_at.strftime("%B %d, %Y at %I:%M %p") %>
    </span>
</li>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

app/views/posts/_form.html.erb
        <%= simple_form_for(@post) do |f| %>
            <%= f.error_notification %>
            <p>
            Created:
            <%= @post.created_at %>
            </p>
            <p>
            Author:
            <%= @post.user.name %>
            </p>

            <%= f.input :title, placeholder: "Enter title" %>

            <div data-no-turbolink>
              <%= f.input :body, placeholder: "Enter Content", class: 'ckeditor' %>
            </div>

            <%= f.button :submit %>
        <% end %>

app/views/posts/_post.html.erb
<li>
  <div class="row">
    <div class="col-md-2">
    <div class="panel panel-info">
    <div class="panel-heading">
      <div class="gravatar">
      <% if post.user.avatar.nil? %>
        <%= image_tag 'http://tt.tennis-warehouse.com/styles/default/xenforo/avatars/avatar_male_m.png' %>
      <% else %>
        <%= image_tag post.user.avatar if !post.user.avatar.nil? %>
      <% end %>
      </div>
      Joined: <%= post.created_at.strftime("%B %d, %Y") %><br>
      Posts: <%= post.user.posts.count %> <br>
      Location: <%= post.user.location %><br>
    </div>
    </div>
  </div>
  <div class="col-md-10">
    <div class="post-header">
    <div class="title">
      <%= link_to post.title, post %> 
    </div>
    <div class="timestamp">
      <%= link_to "#{post.user.name}", user_path(post.user)  %>, 
      <%= post.created_at.strftime("%B %d, %Y at %I:%M %p") %>
    </div>
    </div>
  <div class="content">
    <%= post.body.html_safe %> 
  </div>
  <div class="signature">
    <%= post.user.signature %> 
  </div>
  </div>
  </div>
</li>

<% if false %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
        <span class="body">
            <%= post.body %> 
        </span>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= will_paginate %>
<div class="container">
  <h1> All Posts </h1>
<ul class="posts">
    <%= render @posts %>
</ul>
</div>
<%= will_paginate %>

app/views/posts/new.html.erb
<div class="container">
    <h1>New Post</h1>
    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title"><%= @post.title %></h1>
	<p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago by <%= @post.user.name %>
  <% if @post.user == current_user %>
		| <%= link_to 'Edit', edit_post_path(@post) %> |
		  <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
	</p>
	<p class="body"><%= @post.body %></p>
    <div class="container">
      <h1><%= @post.comments.count %> comments </h1>
        <%= render @post.comments %>


        <% if user_signed_in? %>
          <h1>Add a comment:</h1>
          <%= render "comments/form" %>
        <% else %>
          <strong>If you were logged in, you could add a comment</strong>
        <% end %>
    </div>
</div>

app/views/static_pages/about.html.erb
<div class="container">
<h1>About this app</h1>
<p>
  This is a slightly weird blog app. It is based on MacKenzie Child's video although I've diverged a lot from it. But obviously it's just an app where people can post posts. No one actually has a blog of his own.
</p>

<p>
  Usually, in a blog system, users create a blog with a blog title and add posts to it. Here, people just post. There are no blogs. Unless, MC meant it to be one person's blog. But that is not also clear since everyone can post.
</p>

<p>
  Thus, I am now slowly trying to make it more of a blog. This is my first ROR app. I am learning.
</p>
</div>

app/views/static_pages/contact_us.html.erb
<h1>StaticPages#contact_us</h1>
<p>Find me in app/views/static_pages/contact_us.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container">
  <h1> Recent Posts </h1>
<ul class="posts">
  <%= render @new_posts %>
</ul>
</div>
<div class="container">
  <h1> Recent Comments </h1>
  <%= render @new_comments %>
</div>
<div class="container">
  <h1> New Users </h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Join date</th>
        <th>Posts</th>
      </tr>
    </thead>
    <tbody>
  <%= render @new_users %>
    </tbody>
</table>
</div>

app/views/users/_message.html.erb
<%= simple_form_for([@user.messages.build(sender_id: current_user.id)]) do |f| %>
    <%= f.hidden_field :sender_id, value:  current_user.id %>
    <%= f.hidden_field :receiver_id, value:  @user.id %>
    <%= f.input :body, placeholder: 'Write something' , label: false %>
    <%= f.submit 'Post' %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to "#{user.name}", user_path(user)  %> </td>
  <td><%= user.created_at %> </td>
  <td><%= user.posts.count %> </td>
</tr>

app/views/users/comments.html.erb
<div class="container">
  <h1>  Comments of <%= @user.name %></h1>
  <ul class="comments">
    <%= render @comments %>
  </ul>
</div>

app/views/users/edit.html.erb
<div class="container">
<h1>Update your profile</h1>
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, placeholder: 'Enter name' %>

  <%= f.input :email, placeholder: 'Enter email' %>

  <%= f.input :location, placeholder: 'Enter location'  %>

  <%= f.input :avatar, placeholder: 'Enter url of image'  %>

  <%= f.input :signature, placeholder: 'Enter signature'  %>

  <%= f.input :dob, label: "Date of Birth", as: :date, start_year: Time.now.year - 90, end_year: Time.now.year - 8, order: [:day, :month, :year] %>

  <%= f.input :sex, as: :radio_buttons,
    collection: ["Male", "Female"] %>

  <%= f.button :submit %>
<% end %>
</div>

app/views/users/index.html.erb
<%= will_paginate %>
<div class="container">
	<h2>List of Members</h2>
  <p>This is a list of members sorted by join date:</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Join date</th>
        <th>Posts</th>
      </tr>
    </thead>
    <tbody>
  <%= render @users %>
    </tbody>
</table>
</div>
<%= will_paginate %>

app/views/users/posts.html.erb
<div class="container">
  <h1>  Posts of <%= @user.name %></h1>
  <ul class="posts">
    <%= render @posts %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>Profile of <%= @user.name %></h1>
  
  <div class="row">
    <div class="col-md-2"> 
      <%= image_tag @user.avatar if !@user.avatar.nil? %>
    </div>
    <div class="col-md-10"> 
  <table class="table">
    <tr>
      <td>Joined:</td>
      <td><%= @user.created_at %></td>
      <td><%= time_ago_in_words(@user.created_at) %> ago</td>
    </tr>
    <tr>
      <td>Posts:</td>
      <td><%= @post_count %></td>
      <td><%= link_to "View All Posts", posts_user_path(@user) %></td>
    </tr>
    <tr>
      <td>Comments:</td>
      <td><%= @comment_count %></td>
      <td><%= link_to "View All Comments", comments_user_path(@user) %></td>
    </tr>
  </table>
    </div>
</div>
 </div>
<!-- post message box -->
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
  <%= render 'message' if user_signed_in? %>
    </div>
  </div>
</div>
<div class="container">
  <h1> Recent Messages </h1>
  <ul class="posts">
    <%= render @messages %>
  </ul>
</div>
<div class="container">
  <h1> Recent Posts </h1>
  <ul class="posts">
    <%= render @posts %>
  </ul>
</div>
<div class="container">
  <h1> Recent Comments </h1>
  <%= render @comments %>
</div>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to "Edit Profile", edit_user_path(@user) if user_signed_in? %>
    </div>
  </div>